import type { Counts } from "./phase0";
import type { Phase1Shape } from "./phase1";
import type { Phase2Structure } from "./phase2";
import type { Phase3Narrative } from "./phase3";
import type { RepoHistoryMeta } from "./types";

export function synthesizeAnalysis(args: {
  meta: RepoHistoryMeta;
  shape: Phase1Shape;
  structure: Phase2Structure;
  narrative: Phase3Narrative;
}): string {
  const { meta, shape, structure, narrative } = args;
  const lines: string[] = [];

  lines.push(`# Repo History Analysis - ${meta.repoName}`);
  lines.push("");
  lines.push(
    `Generated by \`lib/repo-history\`. Scope: past ${meta.windowDays} day(s) of commits, anchored to **${meta.windowAnchorMode === "now" ? "wall clock" : "last commit"}** (${meta.windowAnchorIso}).`,
  );
  lines.push(`Window: **${meta.windowFrom} -> ${meta.windowTo}** (committer date, exclusive of to-date).`);
  lines.push(`Branch: **${meta.branch}**.`);
  lines.push(`URL: ${meta.repoUrl}`);
  lines.push("");
  lines.push(
    `Counts: ${meta.totalCommits} commits total, ${meta.totalMerges} merges; ${meta.weekCommits} commits and ${meta.weekMerges} merges inside the window.`,
  );
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(renderOverview(structure));
  lines.push("");
  lines.push("## Timeline (window)");
  lines.push("");
  lines.push(renderTimeline(narrative, countsOf(narrative), meta));
  lines.push("");
  lines.push("### Areas touched in the window");
  lines.push("");
  lines.push(renderChurnNarrative(shape));
  lines.push("");
  lines.push("## Branches");
  lines.push("");
  lines.push(renderBranches(shape));
  lines.push("");
  lines.push("## Ownership");
  lines.push("");
  lines.push(renderOwnership(shape, narrative));
  lines.push("");
  lines.push("## Uncertainties");
  lines.push("");
  lines.push(
    [
      "- **Author vs commit date.** This report uses committer date (`%cd`) for the window and `%ad` per commit, matching the playbook's recommendation to pick one and stick with it. Rebases that rewrite `%cd` will shift entries.",
      "- **No PR / issue context.** Zero merge commits and no remote PR refs in this repo means *why* behind a commit is not recoverable from git alone.",
      "- **Identity fragmentation.** Only one author identity observed in the data; no `.mailmap` dedupe applied.",
      "- **Single large initial scaffold.** If the repo was bootstrapped with a default project commit, pre-scaffold history is not present.",
      "- **No CI / no tests.** Verification of builds, lint, or tests cannot be derived from the metadata alone.",
      meta.windowAnchorMode === "last-commit"
        ? "- **Window anchor.** Window is anchored to the most recent commit's committer date, not wall-clock time. If you want the last 7 calendar days, pass `windowAnchor: 'now'`."
        : "- **Window anchor.** Window is anchored to wall-clock time.",
    ].join("\n"),
  );
  return lines.join("\n");
}

function renderOverview(structure: Phase2Structure): string {
  const pkg = structure.packageJson;
  if (!pkg) {
    if (structure.manifestsPresent.length === 0) {
      return "Unknown project type. No manifests detected.";
    }
    return `Detected manifests: ${structure.manifestsPresent.join(", ")}. No package.json found; cannot infer stack.`;
  }
  const lines: string[] = [];
  const deps = parseSimpleMap(pkg.dependencies);
  const scripts = parseSimpleMap(pkg.scripts);
  const frameworkHints = detectFrameworks(deps);
  if (frameworkHints.length) {
    lines.push(`Stack hint: ${frameworkHints.join(", ")}.`);
  }
  if (scripts.size) {
    const interesting = [...scripts.entries()]
      .filter(([k]) => /^(dev|start|build|test|lint|db|generate)$/.test(k))
      .map(([k, v]) => `${k}=${v}`);
    if (interesting.length) lines.push(`Scripts of note: ${interesting.join(", ")}.`);
  }
  if (structure.treeDepth2.length) {
    lines.push("Top-level tree (depth 2):");
    lines.push("");
    lines.push("```");
    for (const row of structure.treeDepth2) lines.push(row);
    lines.push("```");
  }
  return lines.join("\n");
}

function renderTimeline(
  narrative: Phase3Narrative,
  _counts: Counts,
  meta: RepoHistoryMeta,
): string {
  if (narrative.commits.length === 0) {
    return "_No commits in the window._";
  }
  const lines: string[] = [];
  lines.push("| Date | SHA | Subject | Theme |");
  lines.push("| --- | --- | --- | --- |");
  for (const commit of narrative.commits) {
    const theme = inferTheme(commit);
    lines.push(`| ${commit.date} | ${commit.sha.slice(0, 7)} | ${commit.subject.replace(/\|/g, "\\|")} | ${theme} |`);
  }
  lines.push("");
  lines.push(
    `Window summary: ${narrative.commits.length} commit(s) by ${countDistinctAuthors(narrative)} distinct author(s) between ${meta.windowFrom} and ${meta.windowTo}.`,
  );
  return lines.join("\n");
}

function renderChurnNarrative(shape: Phase1Shape): string {
  if (shape.churn.length === 0) return "_No churn in window._";
  const lines: string[] = [];
  for (const row of shape.churn.slice(0, 10)) {
    lines.push(`- \`${row.path}\` (${row.count} commit${row.count === 1 ? "" : "s"})`);
  }
  if (shape.churn.length > 10) {
    lines.push(`- _(${shape.churn.length - 10} more files)_`);
  }
  return lines.join("\n");
}

function renderBranches(shape: Phase1Shape): string {
  if (shape.branches.length === 0) return "_No remote branches visible._";
  const lines: string[] = [];
  for (const branch of shape.branches.slice(0, 20)) {
    lines.push(`- ${branch.date}  ${branch.ref}  ${branch.author}  ${branch.subject}`);
  }
  if (shape.tags.length > 0) {
    lines.push("");
    lines.push("Tags:");
    for (const tag of shape.tags.slice(0, 10)) {
      lines.push(`- ${tag.date}  ${tag.ref}  ${tag.subject}`);
    }
  }
  return lines.join("\n");
}

function renderOwnership(
  shape: Phase1Shape,
  narrative: Phase3Narrative,
): string {
  if (shape.contributors.length === 0) return "_No contributors in window._";
  const lines: string[] = [];
  lines.push("Authors in window:");
  for (const c of shape.contributors) {
    lines.push(`- ${c.name} <${c.email}> - ${c.count} commit(s)`);
  }
  const fileOwners = new Map<string, Map<string, number>>();
  for (const commit of narrative.commits) {
    for (const row of commit.numstat) {
      const owner = fileOwners.get(row.path) ?? new Map<string, number>();
      owner.set(commit.author, (owner.get(commit.author) ?? 0) + 1);
      fileOwners.set(row.path, owner);
    }
  }
  const busFactor = [...fileOwners.entries()]
    .map(([pathName, owners]) => {
      const sorted = [...owners.entries()].sort((a, b) => b[1] - a[1]);
      const top = sorted[0];
      return {
        pathName,
        topAuthor: top?.[0] ?? "",
        topCount: top?.[1] ?? 0,
        authors: sorted.length,
      };
    })
    .filter((row) => row.authors > 0)
    .sort((a, b) => b.topCount - a.topCount)
    .slice(0, 10);
  if (busFactor.length > 0) {
    lines.push("");
    lines.push("Top files by commit count (bus-factor view):");
    for (const row of busFactor) {
      lines.push(
        `- \`${row.pathName}\` - mostly ${row.topAuthor} (${row.topCount} of ${row.authors} author(s))`,
      );
    }
  }
  return lines.join("\n");
}

function inferTheme(commit: { subject: string }): string {
  const subject = commit.subject.toLowerCase();
  if (/(^|\W)(fix|bug|broken|broken|fix)(|$|\W)/.test(subject)) return "fix";
  if (/(^|\W)(add|new|implement|feature|introduce)(|$|\W)/.test(subject)) return "feature";
  if (/(^|\W)(refactor|cleanup|clean up|restructure|rewrite)(|$|\W)/.test(subject)) return "refactor";
  if (/(^|\W)(doc|readme|comment)(|$|\W)/.test(subject)) return "docs";
  if (/(^|\w)(test|spec)(|$|\W)/.test(subject)) return "tests";
  if (/(^|\W)(ui|visual|style|layout|design)(|$|\W)/.test(subject)) return "ui";
  if (/(^|\W)(perf|optimi[sz]e)(|$|\W)/.test(subject)) return "perf";
  if (/(^|\W)(build|ci|deploy|release)(|$|\W)/.test(subject)) return "build";
  return "misc";
}

function parseSimpleMap(body: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of body.split(/\r?\n/)) {
    const idx = line.indexOf("  ");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 2).trim();
    if (key) map.set(key, value);
  }
  return map;
}

function detectFrameworks(deps: Map<string, string>): string[] {
  const hints: string[] = [];
  if (deps.has("next")) hints.push("Next.js");
  if (deps.has("react")) hints.push("React");
  if (deps.has("vue")) hints.push("Vue");
  if (deps.has("svelte")) hints.push("Svelte");
  if (deps.has("express")) hints.push("Express");
  if (deps.has("fastify")) hints.push("Fastify");
  if (deps.has("@supabase/supabase-js") || deps.has("@supabase/ssr")) hints.push("Supabase");
  if (deps.has("drizzle-orm")) hints.push("Drizzle");
  if (deps.has("prisma")) hints.push("Prisma");
  if (deps.has("openai")) hints.push("OpenAI SDK");
  if (deps.has("tailwindcss")) hints.push("Tailwind");
  return hints;
}

function countDistinctAuthors(narrative: Phase3Narrative): number {
  const authors = new Set<string>();
  for (const commit of narrative.commits) authors.add(commit.author);
  return authors.size;
}

function countsOf(narrative: Phase3Narrative): Counts {
  return {
    totalCommits: narrative.commits.length,
    totalMerges: 0,
    weekCommits: narrative.commits.length,
    weekMerges: 0,
  };
}